### PR TITLE
Added Dark and light Mode

### PR DESCRIPTION
**Pull request by ankit071105**
Added Light and mode Feature  made the webpage completely responsive .
# Image

# video

https://github.com/user-attachments/assets/81459c58-f3bf-4de8-a63c-305cafec4938

### CODE REVIEW

**Comment by AyushMann29** [comment]
There is Connect button is it your screen or own website?

**Comment by ankit071105** [comment]
> There is Connect button is it your screen or own website?

no it not my website but for feature it is looking nice

**Comment by AyushMann29** [comment]
Make the connect button look better or remove it your feature will be merged

**Comment by ankit071105** [comment]
okay @AyushMann29

**Comment by ankit071105** [comment]
# Connect button setup
Screenshot 2024-10-02 at 4 17 02 PM

**Pull request merged**
